-- A TENANT billing ITS OWN subscribers (PPPoE monthly fee, hotspot voucher
-- sales). Distinct from sql/006_platform_billing.sql (the platform billing
-- the tenant). invoice_number is unique per-tenant, not globally — each
-- tenant runs its own invoice numbering sequence.

CREATE TABLE subscriber_invoices (
  id              bigint unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
  tenant_id       bigint unsigned NOT NULL,
  subscriber_id   bigint unsigned NOT NULL,
  invoice_number  varchar(32) NOT NULL,
  currency        char(3) NOT NULL DEFAULT 'IDR',
  subtotal        decimal(14,2) NOT NULL DEFAULT 0,
  tax_amount      decimal(14,2) NOT NULL DEFAULT 0,
  total_amount    decimal(14,2) NOT NULL,
  status          enum('draft','pending','paid','overdue','void') NOT NULL DEFAULT 'draft',
  period_start    date NOT NULL,
  period_end      date NOT NULL,
  due_date        date NOT NULL,
  paid_at         timestamp NULL DEFAULT NULL,
  created_at      timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY subscriber_invoices_tenant_number (tenant_id, invoice_number),
  KEY subscriber_invoices_tenant_created (tenant_id, created_at),
  KEY subscriber_invoices_subscriber (subscriber_id),
  CONSTRAINT fk_subscriber_invoices_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_subscriber_invoices_subscriber FOREIGN KEY (subscriber_id) REFERENCES tenant_subscribers(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE subscriber_payments (
  id                      bigint unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
  invoice_id              bigint unsigned NOT NULL,
  tenant_id               bigint unsigned NOT NULL,
  gateway                 varchar(32) DEFAULT NULL,
  gateway_transaction_id  varchar(128) DEFAULT NULL,
  payment_method          varchar(32) DEFAULT NULL,
  payment_url             varchar(512) DEFAULT NULL,
  amount                  decimal(14,2) NOT NULL,
  currency                char(3) NOT NULL DEFAULT 'IDR',
  status                  enum('pending','settlement','expired','failed','refunded') NOT NULL DEFAULT 'pending',
  raw_payload             json DEFAULT NULL,
  paid_at                 timestamp NULL DEFAULT NULL,
  created_at              timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at              timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY subscriber_payments_invoice (invoice_id),
  KEY subscriber_payments_tenant_created (tenant_id, created_at),
  CONSTRAINT fk_subscriber_payments_invoice FOREIGN KEY (invoice_id) REFERENCES subscriber_invoices(id),
  CONSTRAINT fk_subscriber_payments_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tracks a batch of hotspot vouchers generated for sale (see
-- docs/mikrotik-hotspot-integration.md). The vouchers themselves are still
-- just radcheck/radreply rows scoped by tenant_id — this table only tracks
-- the batch metadata (who generated it, how many, at what price) so a
-- tenant can reconcile "sold 200 vouchers this week" against revenue.
CREATE TABLE voucher_batches (
  id                    bigint unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
  tenant_id             bigint unsigned NOT NULL,
  service_plan_id       bigint unsigned DEFAULT NULL,
  batch_code            varchar(32) NOT NULL,
  quantity              int unsigned NOT NULL,
  price_each            decimal(14,2) NOT NULL,
  generated_by_user_id  bigint unsigned DEFAULT NULL, -- NULL = generated by a script, not a dashboard user
  created_at            timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY voucher_batches_tenant_code (tenant_id, batch_code),
  CONSTRAINT fk_voucher_batches_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  CONSTRAINT fk_voucher_batches_plan FOREIGN KEY (service_plan_id) REFERENCES service_plans(id),
  CONSTRAINT fk_voucher_batches_user FOREIGN KEY (generated_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
