from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformPlan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10)),
                ('max_subscribers', models.PositiveIntegerField(blank=True, null=True)),
                ('max_nas', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'platform_plans',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TenantSubscription',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past due'), ('canceled', 'Canceled')], default='trialing', max_length=10)),
                ('current_period_start', models.DateField()),
                ('current_period_end', models.DateField()),
                ('gateway', models.CharField(blank=True, max_length=32, null=True)),
                ('gateway_subscription_id', models.CharField(blank=True, max_length=128, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='tenants.tenant')),
                ('platform_plan', models.ForeignKey(db_column='platform_plan_id', on_delete=django.db.models.deletion.PROTECT, to='billing.platformplan')),
            ],
            options={
                'db_table': 'tenant_subscriptions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlatformInvoice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('billing_name', models.CharField(blank=True, max_length=255, null=True)),
                ('billing_tax_id', models.CharField(blank=True, max_length=32, null=True)),
                ('billing_address', models.CharField(blank=True, max_length=500, null=True)),
                ('invoice_number', models.CharField(max_length=32, unique=True)),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('void', 'Void')], default='draft', max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('due_date', models.DateField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='platform_invoices', to='tenants.tenant')),
                ('subscription', models.ForeignKey(blank=True, db_column='subscription_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.tenantsubscription')),
            ],
            options={
                'db_table': 'platform_invoices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlatformInvoiceItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('invoice', models.ForeignKey(db_column='invoice_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.platforminvoice')),
            ],
            options={
                'db_table': 'platform_invoice_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlatformPayment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gateway', models.CharField(max_length=32)),
                ('gateway_order_id', models.CharField(blank=True, max_length=128, null=True)),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=128, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=32, null=True)),
                ('payment_url', models.CharField(blank=True, max_length=512, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('gateway_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('settlement', 'Settlement'), ('expired', 'Expired'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('chargeback', 'Chargeback')], default='pending', max_length=10)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(db_column='invoice_id', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.platforminvoice')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='platform_payments', to='tenants.tenant')),
            ],
            options={
                'db_table': 'platform_payments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServicePlan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mikrotik_rate_limit', models.CharField(blank=True, max_length=64, null=True)),
                ('radius_groupname', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='service_plans', to='tenants.tenant')),
            ],
            options={
                'db_table': 'service_plans',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriberSubscription',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past due'), ('canceled', 'Canceled')], default='trialing', max_length=10)),
                ('current_period_start', models.DateField()),
                ('current_period_end', models.DateField()),
                ('gateway', models.CharField(blank=True, max_length=32, null=True)),
                ('gateway_subscription_id', models.CharField(blank=True, max_length=128, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_subscriptions', to='tenants.tenant')),
                ('subscriber', models.ForeignKey(db_column='subscriber_id', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscribers.tenantsubscriber')),
                ('service_plan', models.ForeignKey(db_column='service_plan_id', on_delete=django.db.models.deletion.PROTECT, to='billing.serviceplan')),
            ],
            options={
                'db_table': 'subscriber_subscriptions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriberInvoice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('billing_name', models.CharField(blank=True, max_length=255, null=True)),
                ('billing_address', models.CharField(blank=True, max_length=500, null=True)),
                ('invoice_number', models.CharField(max_length=32)),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('void', 'Void')], default='draft', max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('due_date', models.DateField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_invoices', to='tenants.tenant')),
                ('subscriber', models.ForeignKey(db_column='subscriber_id', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='subscribers.tenantsubscriber')),
                ('subscription', models.ForeignKey(blank=True, db_column='subscription_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.subscribersubscription')),
            ],
            options={
                'db_table': 'subscriber_invoices',
                'managed': False,
                'unique_together': {('tenant', 'invoice_number')},
            },
        ),
        migrations.CreateModel(
            name='SubscriberPayment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gateway', models.CharField(blank=True, max_length=32, null=True)),
                ('gateway_order_id', models.CharField(blank=True, max_length=128, null=True)),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=128, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=32, null=True)),
                ('payment_url', models.CharField(blank=True, max_length=512, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('gateway_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('settlement', 'Settlement'), ('expired', 'Expired'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('chargeback', 'Chargeback')], default='pending', max_length=10)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(db_column='invoice_id', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.subscriberinvoice')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_payments', to='tenants.tenant')),
            ],
            options={
                'db_table': 'subscriber_payments',
                'managed': False,
            },
        ),
    ]
